export const products = [
  {
    id: 1,
    title: 'Woman T-shirt',
    description: 'Red T-shirt from the best material, convinient to wear',
    price: 49,
    discountPercentage: 12.96,
    rating: 4.69,
    stock: 94,
    brand: 'Apple',
    category: 't-shirts',
    thumbnail: '...',
    image: 'https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg',
  },
  {
    id: 2,
    title: 'Clothes bundle',
    description:
      'The best choice of spring clothes for those who can feel the style',
    price: 129,
    discountPercentage: 16,
    rating: 6,
    stock: 100,
    brand: 'Apple',
    category: 'cloth bundle',
    thumbnail: '...',
    image: 'https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg',
  },
  {
    id: 3,
    title: 'suit pack',
    description: 'Perfect designed suit pack',
    price: 299,
    discountPercentage: 11.96,
    rating: 5.69,
    stock: 194,
    brand: 'Apple',
    category: 'backpacks',
    thumbnail: '...',
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
  },
  {
    id: 4,
    title: 'Stylish jacket',
    description: 'A perfect jacket',
    price: 1549,
    discountPercentage: 15.96,
    rating: 7.69,
    stock: 494,
    brand: 'Apple',
    category: 'coats',
    thumbnail: '...',
    image: 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg',
  },
  {
    id: 5,
    title: 'Woman T-shirt',
    description: 'Red T-shirt from the best material, convinient to wear',
    price: 49,
    discountPercentage: 12.96,
    rating: 4.69,
    stock: 94,
    brand: 'Apple',
    category: 't-shirts',
    thumbnail: '...',
    image: 'https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg',
  },
  {
    id: 6,
    title: 'Clothes bundle',
    description:
      'The best choice of spring clothes for those who can feel the style',
    price: 129,
    discountPercentage: 16,
    rating: 6,
    stock: 100,
    brand: 'Apple',
    category: 'cloth bundle',
    thumbnail: '...',
    image: 'https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg',
  },
  {
    id: 7,
    title: 'suit pack',
    description: 'Perfect designed suit pack',
    price: 299,
    discountPercentage: 11.96,
    rating: 5.69,
    stock: 194,
    brand: 'Apple',
    category: 'backpacks',
    thumbnail: '...',
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
  },
  {
    id: 8,
    title: 'Stylish jacket',
    description: 'A perfect jacket',
    price: 1549,
    discountPercentage: 15.96,
    rating: 7.69,
    stock: 494,
    brand: 'Apple',
    category: 'coats',
    thumbnail: '...',
    image: 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg',
  },
];
